minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
artifactProvider:
  name: none
targets:
  - id: release
    name: docker
    source: ghcr.io/getsentry/action-release-image
    target: getsentry/action-release
  - id: latest
    name: docker
    source: ghcr.io/getsentry/action-release-image
    target: getsentry/sentry
    targetFormat: '{{{target}}}:latest'
  - name: github
    tagPrefix: v