name: "Use local Dockerfile"
description: "Use the local Dockerfile to test the action instead of the one on DockerHub"
inputs:
  working_directory:
    description: 'Directory to manipulate Dockerfile in'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Replace image on action.yml
      shell: bash
      run: |
        mv ${{inputs.working_directory}}/action.yml ${{inputs.working_directory}}/previous.yml
        sed "s|docker://ghcr.io/getsentry/action-release-image:latest|Dockerfile|" ${{inputs.working_directory}}/previous.yml >> ${{inputs.working_directory}}/action.yml
        grep "image" ${{inputs.working_directory}}/action.yml
